version: "3"
services:
  database:
    image: "mysql"
    restart: always
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: "testing"
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    ports:
      - "3307:3306"
    container_name: mysql-container
    volumes:
        - mysql_data_volume:/data/db       
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "node-mysql-app"
    depends_on:
      - database
    ports:
      - 4000:3000
volumes:  
   mysql_data_volume:
     driver: local  