version: "3.8"
services:
       database:
         image: mysql
         container_name: maha
       website:
            image: maha152/hello
            container_name: c7
            depends_on: 
               - database 
            ports:
               - "3000:80"        
     
